print("="*60)
print("Welcome To The Interactive Personal Data Collector!")
name=input("please enter your name")
age=int(input("please enter your age"))
height=float(input("please enter your height in meters"))
number=int(input("please enter your favourite number"))
print("="*60)
print("Thank you! Here is the information we collected:")
print(type(name))
print(type(age))
print(type(height))
print(type(number))
print(id(name))
print(id(age))
print(id(height))
print(id(number))
current_year = 2026
birth_year = current_year-age
print("+"*60)
print("Thank you for using the personal data collector. Goodbye!")
